// [MB] Módulo: Tasks / Estilos: CreateTaskModal
// Afecta: CreateTaskModal
// Propósito: Estilos para modal de crear/editar tareas
// Puntos de edición futura: ajustar tokens o layout
// Autor: Codex - Fecha: 2025-08-13

import { StyleSheet } from "react-native";
import { Colors, Spacing, Radii, Elevation, Typography } from "../../theme";

export default StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: Colors.overlay,
    justifyContent: "center",
    alignItems: "center",
  },
  container: {
    width: "90%",
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radii.xl,
    padding: Spacing.large,
    maxHeight: "90%",
    ...Elevation.card,
  },
  title: {
    ...Typography.h1,
    color: Colors.text,
    marginBottom: Spacing.small,
  },
  input: {
    height: 48,
    borderRadius: Radii.lg,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.textMuted + "40",
    paddingHorizontal: Spacing.base,
    color: Colors.text,
    fontSize: 14,
  },
  button: {
    borderRadius: Radii.pill,
    minHeight: 44,
    paddingHorizontal: Spacing.large,
    justifyContent: "center",
    alignItems: "center",
    ...Elevation.card,
  },
  buttonPrimary: {
    backgroundColor: Colors.primary,
  },
  buttonSecondary: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.textMuted + "40",
  },
  buttonText: {
    color: Colors.text,
    fontWeight: "600",
  },
  label: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "600",
    marginTop: Spacing.base,
    marginBottom: Spacing.small,
  },
  subtaskHint: {
    color: Colors.textMuted,
    fontSize: 12,
  },
  row: {
    flexDirection: "row",
    marginBottom: Spacing.base,
    width: "100%",
  },
  optionBtn: {
    paddingVertical: Spacing.tiny,
    paddingHorizontal: Spacing.tiny,
    borderRadius: Radii.md,
    borderWidth: 1,
    borderColor: Colors.textMuted + "40",
    marginRight: Spacing.tiny,
    flexDirection: "row",
    alignItems: "center",
  },
  optionText: {
    color: Colors.text,
    fontSize: 12,
    marginLeft: 4,
  },
  difficultyOptionBtn: {
    flex: 1,
    paddingVertical: Spacing.small,
    borderRadius: Radii.lg,
    borderWidth: 1,
    borderColor: Colors.textMuted + "40",
    alignItems: "center",
    justifyContent: "center",
    marginRight: Spacing.small,
  },
  typeOptionBtn: {
    flex: 1,
    minHeight: 40,
    paddingHorizontal: Spacing.base,
    borderRadius: Radii.pill,
    borderWidth: 1,
    borderColor: Colors.textMuted + "40",
    alignItems: "center",
    justifyContent: "center",
    marginRight: Spacing.small,
  },
  typeOptionText: {
    color: Colors.textMuted,
    fontSize: 14,
    fontWeight: "600",
  },
  elementGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.base,
    marginTop: Spacing.small,
  },
  elementCard: {
    width: "48%",
    borderWidth: 2,
    borderRadius: Radii.lg,
    backgroundColor: Colors.surface,
    paddingVertical: Spacing.base,
    alignItems: "center",
    justifyContent: "center",
    ...(Elevation?.card || {}),
  },
  elementCardActive: {
    shadowOpacity: 0.35,
  },
  elementEmoji: {
    fontSize: 32,
    marginBottom: Spacing.tiny,
  },
  elementTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text,
    textAlign: "center",
  },
  elementCaption: {
    fontSize: 12,
    color: Colors.textMuted,
    textAlign: "center",
    marginTop: Spacing.tiny,
  },
  priorityList: {
    marginTop: Spacing.small,
    gap: Spacing.small,
  },
  priorityRow: {
    width: "100%",
    minHeight: 56,
    borderWidth: 2,
    borderRadius: Radii.lg,
    paddingVertical: Spacing.small,
    paddingHorizontal: Spacing.base,
    alignItems: "center",
    justifyContent: "center",
  },
  priorityTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text,
    textAlign: "center",
  },
  priorityCaption: {
    fontSize: 12,
    color: Colors.textMuted,
    textAlign: "center",
    marginTop: 2,
  },
  tagInputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: Spacing.base,
  },
  tagInput: {
    flex: 1,
    height: 48,
    borderRadius: Radii.lg,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.textMuted + "40",
    paddingHorizontal: Spacing.base,
    color: Colors.text,
    fontSize: 14,
  },
  addTagButton: {
    marginLeft: Spacing.small,
    backgroundColor: Colors.primary,
    padding: Spacing.small,
    borderRadius: Radii.lg,
    justifyContent: "center",
    alignItems: "center",
  },
  tagChip: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    borderWidth: 0.5,
    borderColor: Colors.textMuted,
    paddingHorizontal: Spacing.small,
    paddingVertical: 4,
    marginRight: Spacing.small,
    flexDirection: "row",
    alignItems: "center",
  },
  tagText: {
    color: Colors.text,
    fontSize: 12,
  },
  selectedTagsLabel: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "600",
    marginBottom: Spacing.small,
  },
  subtaskInputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: Spacing.base,
  },
  subtaskInput: {
    flex: 1,
    height: 48,
    borderRadius: Radii.lg,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.textMuted + "40",
    paddingHorizontal: Spacing.base,
    color: Colors.text,
    fontSize: 14,
  },
  addSubtaskButton: {
    marginLeft: Spacing.small,
    backgroundColor: Colors.primary,
    padding: Spacing.small,
    borderRadius: Radii.lg,
    justifyContent: "center",
    alignItems: "center",
  },
  subtaskList: {
    marginTop: Spacing.small,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  subtaskItem: {
    backgroundColor: Colors.surface,
    borderRadius: Radii.lg,
    borderWidth: 1,
    borderColor: Colors.textMuted + "40",
    paddingHorizontal: Spacing.small,
    paddingVertical: 4,
    marginRight: Spacing.small,
    marginBottom: Spacing.small,
    flexDirection: "row",
    alignItems: "center",
  },
  subtaskText: {
    color: Colors.text,
    fontSize: 12,
  },
  removeIcon: {
    marginLeft: Spacing.tiny,
  },
  elementInfoBox: {
    backgroundColor: Colors.surface,
    borderRadius: Radii.lg,
    padding: Spacing.small,
    marginBottom: Spacing.base,
  },
  elementInfoTitle: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "600",
    marginBottom: Spacing.tiny,
  },
  elementInfoDescription: {
    color: Colors.text,
    fontSize: 12,
    marginBottom: Spacing.tiny,
  },
  elementInfoExamples: {
    color: Colors.text,
    fontSize: 12,
    marginBottom: Spacing.tiny,
  },
  elementInfoPurpose: {
    color: Colors.text,
    fontSize: 12,
  },
  alertContainer: {
    position: "absolute",
    bottom: Spacing.xlarge,

    left: Spacing.base,
    right: Spacing.base,
    paddingVertical: Spacing.small,
    paddingHorizontal: Spacing.base,
    borderRadius: 8,
    zIndex: 2,
    alignItems: "center",
  },
  alertText: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "600",
  },
  alertSuccess: {
    backgroundColor: Colors.secondary,
  },
  alertError: {
    backgroundColor: Colors.danger,
  },
});
