// [MB] Module: Planta / Section: actionMechanics
// Purpose: Centralizar la informacion narrativa y numerica de las acciones rapidas
// Author: Codex - Date: 2025-10-30

export const ACTION_MECHANICS = {
  water: {
    title: "Regar",
    category: "core",
    headline: "Prioriza regar cuando el indicador de Agua baje de 55%.",
    summary: "Recupera humedad y extiende la vitalidad del cultivo por 2 horas.",
    cost: [{ type: "mana", amount: 20 }],
    rewards: [{ type: "plant.water", label: "+Agua", amount: 15 }],
    buffs: [{ key: "vitality", label: "Vitalidad", durationMin: 120 }],
    cooldownMin: 120,
    cadence: "2 veces al dia",
    cues: [
      "Si el nivel de Agua baja de 55%.",
      "Tras completar tareas exigentes que drenaron energia.",
    ],
    tips: [
      "Evita regar si Agua supera 85% para prevenir exceso de humedad.",
      "Limpia hojas y maceta minutos despues para potenciar el brillo.",
    ],
    stack: ["Meditar despues del riego mejora el animo de la planta."],
  },
  feed: {
    title: "Alimentar",
    category: "core",
    headline: "Usa nutrientes cuando el indicador este por debajo de 60%.",
    summary: "Recarga el suelo y activa un buff de crecimiento durante 1 hora.",
    cost: [{ type: "coin", amount: 120 }],
    rewards: [{ type: "plant.nutrients", label: "+Nutrientes", amount: 10 }],
    buffs: [{ key: "growth", label: "Crecimiento", durationMin: 60 }],
    cooldownMin: 180,
    cadence: "1 vez al dia",
    cues: [
      "Si Nutrientes esta en amarillo o por debajo de 60%.",
      "Previo a desbloquear una etapa nueva de crecimiento.",
    ],
    tips: [
      "Reserva monedas completando retos diarios antes de alimentar.",
      "Usa Limpiar despues para resaltar el nuevo brillo de la maceta.",
    ],
    stack: ["Buff Crecimiento +1h puede convertir XP extra en proximas acciones."],
  },
  clean: {
    title: "Limpiar",
    category: "core",
    headline: "Ideal entre acciones para mantener Pureza arriba de 70%.",
    summary: "Elimina impurezas y eleva la Pureza de la planta sin costo.",
    cost: [],
    rewards: [{ type: "plant.purity", label: "+Pureza", amount: 10 }],
    buffs: [],
    cooldownMin: 15,
    cadence: "Cada 3-4 interacciones",
    cues: [
      "Despues de regar o alimentar para retirar excedentes.",
      "Si notas el halo con menos brillo o Pureza baja de 65%.",
    ],
    tips: [
      "Aprovecha su cooldown corto para alternarlo con otras acciones.",
      "Usalo antes de tomar capturas de la planta para un look pulido.",
    ],
    stack: ["Limpiar + Meditar ayuda a estabilizar Pureza y Animo."],
  },
  prune: {
    title: "Podar",
    category: "core",
    headline: "Retira hojas secas para mantener Pureza y estimular brotes.",
    summary: "Pequeñas podas mejoran la salud general y el aspecto.",
    cost: [],
    rewards: [
      { type: "plant.purity", label: "+Pureza", amount: 8 },
      { type: "xp", label: "+XP", amount: 10 },
    ],
    buffs: [{ key: "vitality", label: "Vitalidad", durationMin: 30 }],
    cooldownMin: 240,
    cadence: "2-3 veces por semana",
    cues: [
      "Si notas hojas amarillas o puntas secas.",
      "Antes de una fase de crecimiento para ordenar ramas.",
    ],
    tips: [
      "Evita podas agresivas; realiza cortes pequeños y puntuales.",
      "Combina con Limpiar para retirar restos y destacar el brillo.",
    ],
    stack: ["Podar + Regar renueva la planta visual y energéticamente."],
  },
  light: {
    title: "Ajustar luz",
    category: "core",
    headline: "Reorienta la maceta cuando el indicador de Luz baje de 60%.",
    summary: "Limpia hojas y acerca la planta a la ventana para absorber rayos suaves.",
    cost: [],
    rewards: [{ type: "plant.light", label: "+Luz", amount: 12 }],
    buffs: [{ key: "photosynthesis", label: "Fotosíntesis", durationMin: 90 }],
    cooldownMin: 90,
    cadence: "2 veces al día",
    cues: [
      "Si el indicador de Luz está amarillo o llevas varias horas sin sol.",
      "Antes de sesiones de trabajo largas para mantener la energía de la planta.",
    ],
    tips: [
      "Evita luz directa al mediodía; usa cortina o luz artificial suave.",
      "Combina con Neblina para evitar que el follaje se reseque.",
    ],
    stack: ["Luz + Meditar refuerza el mood de ambos."],
  },
  mist: {
    title: "Neblina fresca",
    category: "core",
    headline: "Activa una brisa ligera cuando Pureza o Temperatura bajen de 65%.",
    summary: "Pulveriza agua templada alrededor para estabilizar humedad y ánimos.",
    cost: [],
    rewards: [
      { type: "plant.purity", label: "+Pureza", amount: 6 },
      { type: "plant.temperature", label: "Temperatura estable", amount: 1 },
    ],
    buffs: [{ key: "calmAura", label: "Aura calma", durationMin: 45 }],
    cooldownMin: 60,
    cadence: "1-2 veces al día",
    cues: [
      "Después de una ola de calor o muchas horas frente a pantallas.",
      "Si limpiaste recientemente y quieres sellar el brillo.",
    ],
    tips: [
      "Usa agua filtrada para no dejar manchas en las hojas.",
      "Activa música suave o respiraciones para amplificar el efecto.",
    ],
    stack: ["Neblina + Gratitud conecta el cuidado personal con el de la planta."],
  },
  search: {
    title: "Buscar plagas",
    category: "core",
    headline: "Inspecciona hojas cuando Pureza o Salud bajen de 60%.",
    summary: "Detecta bichos o manchas temprano y protege la planta con un spray ligero.",
    cost: [],
    rewards: [
      { type: "plant.purity", label: "+Pureza", amount: 7 },
      { type: "xp", label: "+XP atención", amount: 8 },
    ],
    buffs: [{ key: "guardian", label: "Guardian verde", durationMin: 120 }],
    cooldownMin: 180,
    cadence: "1 vez por semana",
    cues: [
      "Si notas puntos cafés, telarañas o crecimiento detenido.",
      "Después de traer plantas nuevas al mismo espacio.",
    ],
    tips: [
      "Usa una linterna cálida y revisa el envés de cada hoja.",
      "Anota en el journal los hallazgos para detectar patrones.",
    ],
    stack: ["Buscar plagas + Limpiar asegura que los restos no vuelvan."],
  },
  meditate: {
    title: "Meditar",
    category: "core",
    headline: "Activa cuando necesites XP rapido o requieras bajar la ansiedad.",
    summary: "Completa la respiracion guiada para ganar XP y Calma durante 45 minutos.",
    cost: [{ type: "mana", amount: 10 }],
    rewards: [{ type: "xp", label: "+XP", amount: 30, condition: "al completar guia" }],
    buffs: [{ key: "calm", label: "Calma", durationMin: 45 }],
    cooldownMin: 45,
    cadence: "1-2 veces al dia",
    cues: [
      "Si el indicador de Animo baja de 65%.",
      "Antes de enfrentar una tanda de tareas largas.",
    ],
    tips: [
      "Sincroniza con Regar para aprovechar ambas auras renovadas.",
      "Usa audifonos y cronometra la respiracion para maximizar XP.",
    ],
    stack: ["Combina con Visualizar para reforzar enfoque despues de calmarte."],
  },
  hydrate: {
    title: "Hidratarme",
    category: "ritual",
    headline: "Recuerda hidratarte cada vez que la planta lo necesite.",
    summary: "Te invita a tomar un vaso de agua y suma Monedas por formarte el habito.",
    cost: [],
  rewards: [
      { type: "coin", label: "+Monedas", amount: 3 },
      { type: "streak", label: "+Racha agua", amount: 1 },
    ],
    buffs: [{ key: "vitality", label: "Vitalidad", durationMin: 30 }],
    cooldownMin: 720,
    cadence: "8 vasos al dia (dos bloques de 4)",
    cues: [
      "Completa 4 vasos antes del mediodia y otros 4 por la tarde.",
      "El contador se reinicia cada 12 horas para evitar spam de recompensas.",
    ],
    tips: [
      "Registra tu vaso en un journal rapido para seguir el progreso.",
      "Al completar 8 vasos obtienes un bonus de Monedas adicional.",
    ],
    stack: ["Combinalo con Estirarme para micro descansos completos."],
  },
  stretch: {
    title: "Estirarme",
    category: "ritual",
    headline: "Suelta tension acumulada cada 30 minutos intensos.",
    summary: "Tres estiramientos rapidos activan Vitalidad y resetean postura.",
    cost: [],
    rewards: [],
    buffs: [{ key: "vitality", label: "Vitalidad", durationMin: 30 }],
    cooldownMin: 30,
    cadence: "3 veces al dia",
    cues: [
      "Tras sesiones largas frente a la pantalla.",
      "Antes de volver a trabajar luego de regar o meditar.",
    ],
    tips: [
      "Usa un timer de 30 segundos por estiramiento.",
      "Alterna cuello, hombros y espalda para un reset completo.",
    ],
    stack: ["Estirarme + Hidratarme es una pausa perfecta de 2 minutos."],
  },
  sunlight: {
    title: "Chequeo de luz",
    category: "ritual",
    headline: "Revisa la exposicion de tu espacio para mantener Luz equilibrada.",
    summary: "Abre ventanas o sal unos minutos para cargar el indicador de Luz.",
    cost: [],
    rewards: [],
    buffs: [{ key: "light", label: "Luz", durationMin: 30 }],
    cooldownMin: 90,
    cadence: "2 veces al dia",
    cues: [
      "Si el indicador de Luz cae por debajo de 50%.",
      "Por la manana y a media tarde para ciclos de energia balanceados.",
    ],
    tips: [
      "Aprovecha la salida para respirar profundo y resetear focus.",
      "Evita luz directa intensa; busca claridad difusa.",
    ],
    stack: ["Chequeo de luz + Visualizar metas potencia tu foco con luz natural."],
  },
  visualize: {
    title: "Visualizar metas",
    category: "ritual",
    headline: "Refuerza tu objetivo del dia despues de calmarte o hidratarte.",
    summary: "Imagina el logro final para sumar enfoque y motivacion.",
    cost: [],
    rewards: [],
    buffs: [{ key: "focus", label: "Focus", durationMin: 20 }],
    cooldownMin: 60,
    cadence: "1 vez por bloque de tareas",
    cues: [
      "Antes de iniciar una sesion de trabajo.",
      "Tras completar Meditar para consolidar el estado mental.",
    ],
    tips: [
      "Describe con detalle sensorial el resultado que buscas.",
      "Anota una palabra clave que resuma tu vision.",
    ],
    stack: ["Visualizar + Journaling crea un ancla concreta de tu meta."],
  },
  journal: {
    title: "Journaling flash",
    category: "ritual",
    headline: "Anota una frase para aclarar tu estado mental.",
    summary: "Registrar una idea breve mejora claridad y ordena pensamientos.",
    cost: [],
    rewards: [],
    buffs: [{ key: "clarity", label: "Claridad", durationMin: 20 }],
    cooldownMin: 120,
    cadence: "1 vez por jornada",
    cues: [
      "Al finalizar un bloque de trabajo o antes de dormir.",
      "Cuando sientas ruido mental o emociones mezcladas.",
    ],
    tips: [
      "Escribe sin filtros durante 60 segundos.",
      "Cierra con una intencion concreta para el siguiente bloque.",
    ],
    stack: ["Journaling + Gratitud estabiliza el animo al final del dia."],
  },
  gratitude: {
    title: "Compartir gratitud",
    category: "ritual",
    headline: "Eleva el animo enviando un agradecimiento autentico.",
    summary: "Compartir gratitud refuerza vinculos y sube el estado de animo.",
    cost: [],
    rewards: [],
    buffs: [{ key: "mood", label: "Animo", durationMin: 20 }],
    cooldownMin: 120,
    cadence: "1 vez al dia",
    cues: [
      "Despues de lograr una tarea importante.",
      "Cuando notes que tu energia social esta baja.",
    ],
    tips: [
      "Envia un mensaje real a alguien especifico.",
      "Escribe por que esa persona impacto tu dia.",
    ],
    stack: ["Gratitud + Hidratarme cierra pausas conscientes con energia positiva."],
  },
  restEyes: {
    title: "Descanso de ojos",
    category: "ritual",
    headline: "Aplica la regla 20-20-20 para mantener la vista saludable.",
    summary: "Mira lejos durante 20 segundos para relajar la vista y evitar fatiga.",
    cost: [],
    rewards: [],
    buffs: [{ key: "eyeRest", label: "Descanso visual", durationMin: 10 }],
    cooldownMin: 30,
    cadence: "Cada 30 minutos de pantalla",
    cues: [
      "Configura alarmas o usa temporizadores de productividad.",
      "Aprovecha transiciones entre tareas para parpadear consciente.",
    ],
    tips: [
      "Enfoca un punto a 6 metros y respira profundo mientras lo haces.",
      "Cierra los ojos 5 segundos al final para lubricarlos.",
    ],
    stack: ["Descanso visual + Estirarme es un microbreak integral."],
  },
};
