import { StyleSheet } from "react-native";
import { Colors, Spacing, Radii, Typography } from "../theme";

const SHEET_BG = "rgba(14, 10, 24, 0.92)";

export default StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(4, 2, 10, 0.7)",
  },
  backdropDismiss: {
    ...StyleSheet.absoluteFillObject,
  },
  sheet: {
    flex: 1,
    margin: Spacing.base,
    marginTop: Spacing.large,
    backgroundColor: SHEET_BG,
    borderRadius: Radii.xl,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    padding: Spacing.base,
    gap: Spacing.base,
    shadowColor: Colors.shadow,
    shadowOpacity: 0.35,
    shadowRadius: 26,
    shadowOffset: { width: 0, height: 12 },
    elevation: 20,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerText: {
    flex: 1,
    gap: Spacing.tiny,
    paddingRight: Spacing.small,
  },
  title: {
    ...Typography.h2,
    color: Colors.text,
  },
  subtitle: {
    ...Typography.caption,
    color: Colors.textMuted,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  content: {
    paddingBottom: Spacing.base,
    gap: Spacing.base,
  },
  categoryChips: {
    gap: Spacing.small,
    paddingVertical: Spacing.small,
  },
  categoryChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.tiny,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.tiny,
    borderRadius: Radii.pill,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surfaceAlt,
  },
  categoryChipText: {
    ...Typography.caption,
    fontWeight: "600",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  carousel: {
    gap: Spacing.small,
    paddingVertical: Spacing.small,
  },
  carouselCard: {
    width: 220,
    marginRight: Spacing.small,
    borderRadius: Radii.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.base,
    gap: Spacing.small,
    backgroundColor: Colors.surfaceAlt,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  carouselHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.small,
  },
  carouselIcon: {
    width: 40,
    height: 40,
    borderRadius: Radii.md,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.tiny,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  badge: {
    borderRadius: Radii.pill,
    paddingHorizontal: Spacing.small,
    paddingVertical: 2,
    borderWidth: 1,
  },
  badgeText: {
    ...Typography.caption,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  newBadge: {
    borderRadius: Radii.pill,
    paddingHorizontal: Spacing.small,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.45)",
    backgroundColor: "rgba(255,255,255,0.1)",
  },
  newBadgeText: {
    ...Typography.caption,
    fontSize: 10,
    lineHeight: 12,
    color: Colors.text,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  carouselTitle: {
    ...Typography.title,
    color: Colors.text,
  },
  carouselChip: {
    alignSelf: "flex-start",
    borderRadius: Radii.pill,
    paddingHorizontal: Spacing.small,
    paddingVertical: Spacing.tiny,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  carouselChipText: {
    ...Typography.caption,
    color: Colors.text,
    fontWeight: "600",
  },
  timeline: {
    marginTop: Spacing.base,
    gap: Spacing.small,
  },
  timelineRow: {
    flexDirection: "row",
    gap: Spacing.small,
  },
  timelineMarkerWrap: {
    alignItems: "center",
  },
  timelineMarker: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineConnector: {
    width: 1,
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.12)",
    marginTop: 4,
  },
  timelineText: {
    flex: 1,
    paddingBottom: Spacing.small,
    borderBottomWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    gap: Spacing.tiny / 2,
  },
  timelineTitle: {
    ...Typography.body,
    color: Colors.text,
    fontWeight: "600",
  },
  timelineReward: {
    ...Typography.caption,
    marginTop: 2,
  },
  timelineBadges: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.tiny,
    flexWrap: "wrap",
  },
  promoCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.small,
    paddingVertical: Spacing.small,
    paddingHorizontal: Spacing.base,
    borderRadius: Radii.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surfaceAlt,
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 12,
  },
  promoIcon: {
    width: 40,
    height: 40,
    borderRadius: Radii.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  promoText: {
    flex: 1,
    gap: Spacing.tiny / 2,
  },
  promoTitle: {
    ...Typography.body,
    color: Colors.text,
    fontWeight: "600",
  },
  promoDescription: {
    ...Typography.caption,
    color: Colors.textMuted,
  },
  pressed: {
    opacity: 0.85,
  },
});
