// [MB] Módulo: Estado / Sección: Assets de tienda
// Afecta: ShopScreen y ShopItemCard
// Propósito: Centralizar imágenes por categoría y SKU para la tienda
// Puntos de edición futura: añadir variantes por rareza y packs estacionales
// Autor: Codex - Fecha: 2025-11-21

export const SHOP_ITEM_ASSET_MAP = {
  // Potions
  "shop/potions/p1": require("../../assets/potions/pocion de sabiduria.png"),
  "shop/potions/p2": require("../../assets/potions/Poción de Sabiduría Mayor.png"),
  "shop/potions/p3": require("../../assets/potions/relampago de foco.png"),
  "shop/potions/p4": require("../../assets/potions/crital de mana.png"),
  "shop/potions/p5": require("../../assets/potions/critalmagico.png"),
  "shop/potions/p6": require("../../assets/potions/pocion verde.png"),
  "shop/potions/p7": require("../../assets/potions/potion lila.png"),
  "shop/potions/p8": require("../../assets/potions/Escudo de Racha 24h.png"),
  "shop/potions/p9": require("../../assets/potions/Borrador Arcano.png"),
  "shop/potions/p10": require("../../assets/potions/elixir de energia.png"),
  "shop/potions/p11": require("../../assets/potions/Esencia Ígnea.png"),
  "shop/potions/p12": require("../../assets/potions/Esencia de Mareas.png"),
  "shop/potions/p13": require("../../assets/potions/Esencia Terraria.png"),
  "shop/potions/p14": require("../../assets/potions/Esencia de Cierzo.png"),
  "shop/potions/p15": require("../../assets/potions/Transmutador Áureo.png"),
  "shop/potions/p16": require("../../assets/potions/Eco-sérum Restaurador.png"),
  "shop/potions/p17": require("../../assets/potions/Mist Calmante.png"),
  "shop/potions/p18": require("../../assets/potions/Ímpetu Arcano.png"),
  "shop/potions/p19": require("../../assets/potions/Tónico de Prosperidad.png"),
  "shop/potions/p20": require("../../assets/potions/Esencia Temporal.png"),
  "shop/potions/p21": require("../../assets/potions/Neblina de Atemporalidad.png"),
  "shop/potions/p22": require("../../assets/potions/Fénix Embotellado.png"),
  "shop/potions/p23": require("../../assets/potions/Sello del Alba.png"),
  "shop/potions/u_green_potion": require("../../assets/potions/Infusión Herbal.png"),
  "shop/potions/u_mana_crystal": require("../../assets/tools/Fragmento Resonante.png"),
  "shop/potions/u_magic_crystal": require("../../assets/tools/Cristal Mágico.png"),
  "shop/potions/u_energy_elixir": require("../../assets/potions/Ampolla Dynamo.png"),
  "shop/potions/u_purple_potion": require("../../assets/potions/Poción Nebulosa.png"),
  "shop/potions/u_focus_lightning": require("../../assets/potions/Rayo Sináptico.png"),
  "shop/potions/u_wisdom_potion": require("../../assets/potions/Tónica Visionaria.png"),
  "shop/potions/u_time_potion": require("../../assets/potions/pocion temporal.png"),

  // Seeds / Plants
  "shop/seeds/u_amapola": require("../../assets/plants/amapolaflower.png"),
  "shop/seeds/u_daisy": require("../../assets/plants/daisyflower.png"),
  "shop/seeds/u_ortiga": require("../../assets/plants/ortiga.png"),
  "shop/seeds/u_palm": require("../../assets/plants/palm.png"),
  "shop/seeds/u_dandelion1": require("../../assets/plants/dandelionstage1.png"),
  "shop/seeds/u_abedul": require("../../assets/plants/abedul.png"),
  "shop/seeds/u_hibiscus": require("../../assets/plants/hibiscoflower.png"),
  "shop/seeds/u_lavanda": require("../../assets/plants/lavanda.png"),
  "shop/seeds/u_bell": require("../../assets/plants/bell.png"),
  "shop/seeds/u_pine": require("../../assets/plants/pine.png"),
  "shop/seeds/u_sauce": require("../../assets/plants/sauce.png"),
  "shop/seeds/u_apple": require("../../assets/plants/appletree.png"),
  "shop/seeds/u_frailejon": require("../../assets/plants/frailejon.png"),
  "shop/seeds/u_baobab": require("../../assets/plants/baobabmistico.png"),
  "shop/seeds/u_orchid": require("../../assets/plants/orquid.png"),
  "shop/seeds/u_roble": require("../../assets/plants/roble.png"),
  "shop/seeds/s1": require("../../assets/plants/loto.png"),
  "shop/seeds/u_bonsai": require("../../assets/plants/bonsai.png"),
  "shop/seeds/u_carnivora": require("../../assets/plants/carnivora.png"),
  "shop/seeds/u_mushroom": require("../../assets/plants/mushroom.png"),
  "shop/seeds/u_sunflower": require("../../assets/plants/sunflower.png"),
  "shop/seeds/u_paraiso": require("../../assets/plants/avedelparaisomisticaflower.png"),
  "shop/seeds/s10": require("../../assets/plants/sakura.png"),
  "shop/seeds/u_magic_rose": require("../../assets/plants/magicrose.png"),
  "shop/seeds/u_robleantiguo": require("../../assets/plants/robleantiguo.png"),
  "shop/seeds/u_secuoya": require("../../assets/plants/secuoya.png"),
  "shop/seeds/u_dandelion2": require("../../assets/plants/dandelionstage2.png"),
  "shop/seeds/u_tree_life": require("../../assets/plants/arboldelavida.png"),
  "shop/seeds/p6": require("../../assets/easter eggs/Semilla Fénix Bebé.png"),
  "shop/seeds/s11": require("../../assets/plants/Mandrágora Cantarina.png"),
  "shop/seeds/s12": require("../../assets/plants/Árbol del Mundo.png"),
  "shop/seeds/u_cactus_luna": require("../../assets/plants/Cactus Lunar.png"),

  // Tools
  "shop/tools/u_shovel": require("../../assets/tools/pala.png"),
  "shop/tools/u_cure_plant": require("../../assets/tools/curarplanta.png"),
  "shop/tools/t7": require("../../assets/tools/Fertilizante Alquímico.png"),
  "shop/tools/t8": require("../../assets/tools/Guantes Maestros.png"),
  "shop/tools/u_bellows": require("../../assets/tools/Regadera Compacta.png"),
  "shop/tools/t1": require("../../assets/tools/Regadera de Nubes.png"),
  "shop/tools/t3": require("../../assets/tools/Pala de Mitril.png"),
  "shop/tools/t6": require("../../assets/tools/Lámpara Arcana.png"),
  "shop/tools/t10": require("../../assets/tools/Mochila Sin Fondo.png"),
  "shop/tools/u_chest": require("../../assets/tools/baul.png"),
  "shop/tools/u_compass": require("../../assets/tools/brujulamistica.png"),
  "shop/tools/u_dwarf_axe": require("../../assets/tools/hacha enana.png"),
  "shop/tools/u_quill": require("../../assets/tools/pluma.png"),
  "shop/tools/u_ancestral_shovel": require("../../assets/tools/Pala Ancestral.png"),
  "shop/tools/t2": require("../../assets/tools/Caldero de Mana.png"),
  "shop/tools/t4": require("../../assets/tools/Tijeras de Oro.png"),
  "shop/tools/t9": require("../../assets/cosmeticos/Amuleto Suerte.png"),
  "shop/tools/u_spellbook": require("../../assets/tools/libro de hechizos.png"),
  "shop/tools/u_scroll": require("../../assets/tools/pergaminomistico.png"),
  "shop/tools/u_magic_clock": require("../../assets/tools/Reloj de Arena Cósmico.png"),
  "shop/tools/u_lunar_scepter": require("../../assets/tools/Cetro Lunar.png"),
  "shop/tools/u_solar_scepter": require("../../assets/tools/Cetro Solar.png"),
  "shop/tools/u_truth_orb": require("../../assets/tools/Orbe de la Verdad.png"),
  "shop/tools/u_time_shield": require("../../assets/tools/escudo temporal.png"),
  "shop/tools/u_masterkey": require("../../assets/tools/masterkey.png"),
  "shop/tools/u_ring": require("../../assets/tools/ring.png"),
  "shop/tools/u_elf_wand": require("../../assets/tools/varitaelfica1.png"),
  "shop/tools/t5": require("../../assets/cosmeticos/Maceta Rápida.png"),
  "shop/tools/t11": require("../../assets/easter eggs/Huevo Místico.png"),
  "shop/tools/u_rope": require("../../assets/tools/Sello Rúnico.png"),
  "shop/tools/u_sarcophagus": require("../../assets/tools/Sarcófago Rúnico.png"),
  "shop/tools/u_chrono_plume": require("../../assets/tools/relogmagico.png"),

  // Cosmetics
  "shop/cosmetics/c1": require("../../assets/cosmeticos/maceta dorada.png"),
  "shop/cosmetics/c2": require("../../assets/cosmeticos/maceta dorada.png"),
  "shop/cosmetics/c3": require("../../assets/cosmeticos/maceta dorada.png"),
  "shop/cosmetics/c4": require("../../assets/cosmeticos/maceta dorada.png"),
  "shop/cosmetics/c5": require("../../assets/cosmeticos/marcosaura/aura de fuego.png"),
  "shop/cosmetics/c6": require("../../assets/cosmeticos/marcosaura/aura de agua.png"),
  "shop/cosmetics/c7": require("../../assets/cosmeticos/marcosaura/aura nebulosa.png"),
  "shop/cosmetics/c8": require("../../assets/cosmeticos/sombrero encantado.png"),
  "shop/cosmetics/c9": require("../../assets/cosmeticos/sombrero encantado.png"),
  "shop/cosmetics/c10": require("../../assets/cosmeticos/sombrero encantado.png"),
  "shop/cosmetics/u_aura_arcane": require("../../assets/cosmeticos/marcosaura/aura arcana.png"),
  "shop/cosmetics/u_aura_rainbow": require("../../assets/cosmeticos/marcosaura/aura arcoiris.png"),
  "shop/cosmetics/u_aura_water": require("../../assets/cosmeticos/marcosaura/aura de agua.png"),
  "shop/cosmetics/u_aura_fire": require("../../assets/cosmeticos/marcosaura/aura de fuego.png"),
  "shop/cosmetics/u_aura_leaves": require("../../assets/cosmeticos/marcosaura/aura hojas susurrantes.png"),
  "shop/cosmetics/u_aura_nebula": require("../../assets/cosmeticos/marcosaura/aura nebulosa.png"),
  "shop/cosmetics/u_aura_wind": require("../../assets/cosmeticos/marcosaura/auraviento.png"),
  "shop/cosmetics/u_aura_earth": require("../../assets/cosmeticos/marcosaura/auta de tierra.png"),
  "shop/cosmetics/u_butterfly_wing": require("../../assets/cosmeticos/ala de mariposa.png"),
  "shop/cosmetics/u_royal_crown": require("../../assets/cosmeticos/coronareal.png"),
  "shop/cosmetics/u_gold_pot": require("../../assets/cosmeticos/maceta dorada.png"),
  "shop/cosmetics/u_enchanted_hat": require("../../assets/cosmeticos/sombrero encantado.png"),
  "shop/cosmetics/u_basic_hat": require("../../assets/cosmeticos/Sombrero Simple.png"),
  "shop/cosmetics/u_basic_glasses": require("../../assets/cosmeticos/Gafas Simples.png"),
  "shop/cosmetics/u_aura_golden": require("../../assets/cosmeticos/marcosaura/Aura Dorada.png"),

  // Pets
  "shop/pets/p1": require("../../assets/easter eggs/Huevo de Slime.png"),
  "shop/pets/p3": require("../../assets/pets/Búho Mensajero.png"),
  "shop/pets/p4": require("../../assets/pets/Dragón de Bolsillo.png"),
  "shop/pets/p5": require("../../assets/pets/espíritu del Bosque.png"),
  "shop/pets/p6": require("../../assets/pets/Fénix Bebé.png"),
  "shop/pets/u_ant": require("../../assets/pets/ant.png"),
  "shop/pets/u_arturo1": require("../../assets/pets/arturo1.png"),
  "shop/pets/u_arturo2": require("../../assets/pets/arturo2.png"),
  "shop/pets/u_slug": require("../../assets/pets/babosa.png"),
  "shop/pets/u_bee": require("../../assets/pets/bee.png"),
  "shop/pets/u_bug1": require("../../assets/pets/bug1.png"),
  "shop/pets/u_bunny": require("../../assets/pets/bunny.png"),
  "shop/pets/u_butterfly": require("../../assets/pets/butterfly.png"),
  "shop/pets/u_snail": require("../../assets/pets/caracol.png"),
  "shop/pets/u_woodlouse": require("../../assets/pets/cochinilla.png"),
  "shop/pets/u_oruga": require("../../assets/pets/oruga.png"),
  "shop/pets/u_cocoa": require("../../assets/pets/cocoa.png"),
  "shop/pets/u_deer": require("../../assets/pets/deer.png"),
  "shop/pets/u_dragon": require("../../assets/pets/dragon.png"),
  "shop/pets/u_fly": require("../../assets/pets/fly.png"),
  "shop/pets/u_fox": require("../../assets/pets/fox.png"),
  "shop/pets/u_goldfish": require("../../assets/pets/goldenfish.png"),
  "shop/pets/u_fairy": require("../../assets/pets/hada.png"),
  "shop/pets/u_hummingbird": require("../../assets/pets/hummingbird.png"),
  "shop/pets/u_ladybug": require("../../assets/pets/ladybug.png"),
  "shop/pets/u_jaguar": require("../../assets/pets/jaguar mistico.png"),
  "shop/pets/u_merlin": require("../../assets/pets/merlin.png"),
  "shop/pets/u_owl": require("../../assets/pets/owl.png"),
  "shop/pets/u_moth": require("../../assets/pets/polilla.png"),
  "shop/pets/u_orca": require("../../assets/pets/Orca Mística.png"),
  "shop/pets/u_pulpo": require("../../assets/pets/pulpo.png"),
  "shop/pets/u_spider": require("../../assets/pets/spider.png"),
  "shop/pets/u_squirrel": require("../../assets/pets/squirrel.png"),
  "shop/pets/u_tokyo": require("../../assets/pets/tokyo.png"),
  "shop/pets/u_turtle": require("../../assets/pets/turtle.png"),
  "shop/pets/u_unicorn": require("../../assets/pets/unicorn.png"),
  "shop/pets/u_whale": require("../../assets/pets/Ballena Jorobada Mística.png"),
  "shop/pets/u_worm": require("../../assets/pets/worm.png"),
};
