// [MB] Modulo: Home / Estilos: HomeWelcomeCard
// Afecta: HomeWelcomeCard
// Proposito: Estilos para tarjeta de bienvenida con KPIs
// Puntos de edicion futura: sombras y blur avanzado
// Autor: Codex - Fecha: 2025-10-07 (V6)

import { StyleSheet } from "react-native";
import { Colors, Spacing, Radii, Typography, ElementAccents } from "../../theme";

export default StyleSheet.create({
  wrapper: {
    position: "relative",
    borderRadius: Radii.md,
    overflow: "visible",
    shadowColor: Colors.shadow,
    shadowOpacity: 0.35,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  blur: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: Radii.md,
  },
  blurFallback: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: Radii.lg,
    backgroundColor: Colors.overlay,
  },
  container: {
    position: "relative",
    borderRadius: Radii.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: "rgba(18, 14, 36, 0.74)",
    overflow: "hidden",
  },
  orbitContainer: {
    position: "absolute",
    top: -18,
    left: -18,
    right: -18,
    bottom: -18,
    borderRadius: Radii.lg + 18,
    justifyContent: "center",
    alignItems: "center",
  },
  orbitRing: {
    width: "100%",
    height: "100%",
    borderRadius: Radii.lg + 18,
    padding: 2,
    overflow: "hidden",
  },
  orbitInner: {
    flex: 1,
    borderRadius: Radii.lg + 16,
    backgroundColor: "rgba(18, 14, 36, 0.9)",
  },
  neonLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  neonBlob: {
    position: "absolute",
    borderRadius: 180,
    opacity: 0.9,
    overflow: "hidden",
  },
  neonBlobGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 180,
  },
  neonBlur: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: Radii.lg,
    opacity: 0.7,
  },
  neonBlurFallback: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(12, 9, 26, 0.4)",
  },
  lensLayer: {
    position: "absolute",
    width: "150%",
    height: "150%",
    left: "-25%",
    top: "-25%",
    borderRadius: 480,
    backgroundColor: "rgba(255, 120, 189, 0.12)",
    shadowColor: Colors.primary,
    shadowOpacity: 0.16,
    shadowRadius: 38,
    shadowOffset: { width: 0, height: 0 },
  },
  content: {
    paddingTop: Spacing.base,
    paddingBottom: Spacing.base,
    paddingHorizontal: Spacing.base,
    gap: Spacing.small,
  },
  edgeSheen: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: Radii.xl,
    opacity: 0.28,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.small,
    marginBottom: Spacing.tiny,
  },
  headerTextBlock: {
    flex: 1,
    gap: Spacing.tiny / 2,
  },
  avatarWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 2,
    backgroundColor: Colors.surface,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarInner: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
    overflow: "hidden",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarStatus: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: Colors.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.border,
  },
  avatarStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.success,
  },
  title: {
    ...Typography.h2,
    color: Colors.text,
    flexShrink: 1,
  },
  subtitle: {
    ...Typography.caption,
    color: Colors.textMuted,
    fontStyle: "italic",
    marginTop: 0,
    marginBottom: Spacing.small,
  },
  agendaCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.small,
    borderRadius: Radii.lg,
    padding: Spacing.small,
    backgroundColor: "rgba(0,0,0,0.25)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  agendaAccent: {
    width: 4,
    height: "100%",
    borderRadius: Radii.pill,
    backgroundColor: Colors.danger,
  },
  agendaTextBlock: {
    flex: 1,
    gap: Spacing.tiny / 2,
  },
  agendaLabel: {
    ...Typography.micro,
    color: Colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  agendaTitle: {
    ...Typography.body,
    color: Colors.text,
    fontWeight: "700",
  },
  agendaIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderWidth: 1,
    borderColor: Colors.border,
  },
  kpiRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: Spacing.small,
    marginTop: 0,
    marginBottom: Spacing.small,
  },
  kpiBox: {
    flex: 1,
    minWidth: 90,
    paddingVertical: Spacing.small,
    paddingHorizontal: Spacing.small,
    borderRadius: Radii.lg,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    justifyContent: "center",
    alignItems: "center",
    gap: Spacing.tiny / 2,
  },
  kpiLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.tiny / 2,
  },
  footerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.tiny,
    marginTop: Spacing.small,
    paddingVertical: Spacing.small,
    width: "100%",
    borderRadius: Radii.md,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.25)",
    shadowColor: Colors.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 6,
  },
  footerText: {
    ...Typography.button,
    color: Colors.text,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  kpiNumber: {
    ...Typography.h2,
    color: Colors.text,
    fontWeight: "700",
  },
  kpiLabel: {
    ...Typography.caption,
    color: Colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
});
